### ISSUE TITLE
SwarmMemberAddressProvider access to Docker Engine

### ISSUE THREAD

**Issue by robinroos** [bitsofinfo/hazelcast-docker-swarm-discovery-spi#28]
Hello,

Having first tried DNSRR I am now looking into SwarmMemberAddressProvider for cluster node discovery. 

I asked our infrastructure people to provide the necessary parameter value for ${swarmMgrUri} and received the following response:

“I've had a look at this, and if it's connecting to the docker daemon over https to get information on the swarm it would require a massive rearchitecting of the swarm setup, as we'd have to open up some dangerous access, and then make sure we secured it properly, and we'd need to generate certificates for all the servers, and get them injected into the containers at run time.  This isn't the right way to approach this issue.”

if SWARM_MGR_URI is overriding DOCKER_HOST, perhaps it is an optional parameter after all?

I’m hoping that things are actually simpler than I have made them out to be, but at this stage I lack a route forward to achive hazelcast cluster node discovery. 

Thanks, Robin.

**Comment by bitsofinfo** [comment]
If you are not using the DNSRR method, the "swarmMgrUri" is simply a variable name that represents an endpoint (socket or http/s endpoint) to directly get the peer level information needed to form a cluster. In order to work this needs access to some endpoint that presents the Docker API for swarm services/tasks/network information etc. There are numerous ways access to this can be secured or proxied, republished etc (i.e. such as https://github.com/Tecnativa/docker-socket-proxy). If your infrastructure team is not willing to work with you on getting access to that information, then there simply is no other way for hazelcast to discover your services overlay network "peers" and you are SOL. You might have to start looking at another hazelcast discovery SPI other than this one.
